apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-client-backend
  namespace: oc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-client-backend
  template:
    metadata:
      labels:
        app: oc-client-backend
    spec:
      containers:
        - name: app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production